### ISSUE TITLE
rpng_chunk_remove_from_memory corruipts png sometimes

### ISSUE THREAD

**Issue by takase1121** [raysan5/rpng#1]
```c
if (exclusive)
		{
			newbuf = rpng_chunk_remove_from_memory(buffer, "tEXt", &fsize);
			free(buffer);
			buffer = rpng_chunk_write_from_memory(newbuf, chunk, &newfsize);
			free(newbuf);
			fwrite(buffer, sizeof(char), newfsize, output);
			free(buffer);
		}
```
here is a snippet from my program that will remove all `tEXt` chunks from the png and writes a new one to it. I tested it with a png file that has a single `tEXt` chunk in it and it worked fine. However, if the png file has multiple `tEXt` chunks in it, it seems to corrupt the png file (but still viewable).

I use [tweakpng](http://entropymine.com/jason/tweakpng/) to inspect the png individually. 

[the png files](https://github.com/raysan5/rpng/files/4925674/png.zip)

Perhaps I did something wrong with it. If so, feel free to point it out.

Thanks.

**Comment by raysan5** [comment]
@takase1121 thanks for reporting! I'll review it as soon as possible.

**Comment by takase1121** [comment]
Sorry but I found the problem. It was due to my incorrect use of `fopen` and not related to rpng. Sorry for wasting your time, and have a good day!

**Comment by raysan5** [comment]
@takase1121 Glad to know it was not a rpng issue! 👍😄
