### ISSUE TITLE
rpng_create_image bad adaptive filter type

### ISSUE THREAD

**Issue by Shylie** [raysan5/rpng#2]
calling `rpng_create_image` with 3-4 color channels and 8-bit color depth creates an image with bad adaptive filter type

I don't understand how the PNG format works, but I have noted that a proper image is made when the filter type is always 0, instead of determined by an algorithm from lines 484-494 in rpng.h.

Now, this workaround is not a good solution, as it results in poor/no compression.

```diff
best_filter = 0;
- int best_value = sum_value[0];

- for (int filter = 1; filter < 5; filter++)
- {
-    if (sum_value[filter] < best_value)
-    {
-        best_value = sum_value[filter];
-        best_filter = filter;
-    }
- }
```

**Comment by raysan5** [comment]
@Shylie I investigated about it and it seems several libraries use that approach, actually, I think I found it in the official PNG documentation... I imagine there could be also other options, feel free to investigate it.

**Comment by raysan5** [comment]
I'm closing this issue, there could be multiple options to select the best filter, rpng just implements one valid one.
