### ISSUE TITLE
char overflow in rpng.h (line 424)

### ISSUE THREAD

**Issue by alexmambov** [raysan5/rpng#6]
Warning pops up while building an example (**rpng_test_suite.c**) with gcc 11.2.0 on linux with command like: 
`$ gcc -o rpng_test_suite rpng_test_suite.c -fPIC -std=c99 -Wall -Wpedantic`

In file included from rpng_test_suite.c:14:
../src/rpng.h:424:33: warning: overflow in conversion from ‘int’ to ‘char’ changes value from ‘137’ to ‘-119’ [-Woverflow]
  424 | const char png_signature[8] = { 0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a }; // PNG Signature

or while building **rpng.h** itself as shared library with commands like:
```
$ cp src/rpng.h /src/rpng.c
$ gcc -o rpng.so src/rpng.c -shared -fPIC -DRPNG_IMPLEMENTATION -DRPNG_DEFLATE_IMPLEMENTATION -std=c99 -Wall -Wpedantic
```
Warning dissappears when I change line 424 in **rpng.h** to `const unsigned char png_signature[8] = { 0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a }; // PNG Signature`

**Comment by raysan5** [comment]
@alexmambov Oh! Good catch! Just changing it!

**Comment by raysan5** [comment]
Updated: https://github.com/raysan5/rpng/commit/b147ea0f19f0f06cefc5751b0be667a18c1d3df2
